#version 460

#include "RayTracingGlobal.glsl"
#include "../PBR.glsl"
#include "../Utils/random.glsl"

layout (location = 1) rayPayloadInEXT ShadowPayload shadowPayload;

hitAttributeEXT vec3 attribs;

layout (set = 1, binding = 1, std430) readonly buffer EntityDescBuffer {EntityDesc entityDescs[];} entityDescBuffer;

void main()
{
    EntityDesc entityDesc = entityDescBuffer.entityDescs[gl_InstanceCustomIndexEXT];
    if ((gl_IncomingRayFlagsEXT & gl_RayFlagsSkipClosestHitShaderEXT) != 0)
    {
        if ((entityDesc.renderOptions & ENTITY_RENDER_OPTION_CAST_SHADOW) == 0) {
            ignoreIntersectionEXT;
        }

        float opacity = clamp(entityDesc.pbr.opacity, 0.0, 1.0);
        if (opacity >= 0.999) {
            shadowPayload.opacity = 1.0;
            shadowPayload.opaqueShadowed = true;
            terminateRayEXT;
        }

        shadowPayload.opacity += (1.0 - shadowPayload.opacity) * opacity;
        if (shadowPayload.opacity >= 0.999) {
            shadowPayload.opacity = 1.0;
            shadowPayload.opaqueShadowed = true;
            terminateRayEXT;
        }

        ignoreIntersectionEXT;
    }
}