#version 460
#extension GL_EXT_ray_tracing: require

#include "RayTracingGlobal.glsl"
#include "../Utils/random.glsl"

layout (set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout (set = 0, binding = 1, rgba32f) uniform image2D image[2];
layout (set = 0, binding = 2, rgba32f) uniform image2D worldPosImage[2];
layout (set = 0, binding = 3, rgba32f) uniform image2D shadowTermImage[2];
layout (set = 0, binding = 4, rgba32f) uniform image2D rayTracingGuideImage[2];

layout (location = 0) rayPayloadEXT hitPayLoad payload;

layout (push_constant) uniform PushConstant {
    int rayTracingImageIndex;
} pushConstant;

void main()
{
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5f, 0.5f);
    const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;
    vec4 origin = ubo.inverseViewMatrix * vec4(0, 0, 0, 1);
    vec4 target = ubo.inverseProjectionMatrix * vec4(d, 1, 1);
    vec4 direction = ubo.inverseViewMatrix * vec4(normalize(target.xyz), 0);
    uint rayFlags = gl_RayFlagsNoneEXT;
    float tMin = 0.001;
    float tMax = 10000.0;

    payload.opacity = 0;
    payload.hitValue = vec3(0.0, 0.0, 0.0);
    payload.accumulatedDistance = 0;
    payload.bounceCount = 0;
    payload.isBouncing = false;
    payload.throughput = vec3(1.0);
    payload.primaryShadowVisibility = 1.0;
    payload.primaryDirectLighting = vec3(0.0);
    payload.closestHitWorldPos = vec4(0);
    payload.primaryMaterialGuide = vec4(0);
    payload.recursionDepth = 0;

    traceRayEXT(topLevelAS,
                rayFlags,
                DEFAULT_RENDER_LAYER_MASK,
                0,
                0,
                0,
                origin.xyz,
                tMin,
                direction.xyz,
                tMax,
                0
    );

    vec3 linearColor = max(payload.hitValue, vec3(0.0));
    imageStore(image[pushConstant.rayTracingImageIndex], ivec2(gl_LaunchIDEXT.xy), vec4(linearColor, 1.0));
    imageStore(worldPosImage[pushConstant.rayTracingImageIndex], ivec2(gl_LaunchIDEXT.xy), payload.closestHitWorldPos);
    imageStore(rayTracingGuideImage[pushConstant.rayTracingImageIndex], ivec2(gl_LaunchIDEXT.xy), payload.primaryMaterialGuide);
    imageStore(shadowTermImage[pushConstant.rayTracingImageIndex],
               ivec2(gl_LaunchIDEXT.xy),
               vec4(max(payload.primaryDirectLighting, vec3(0.0)), clamp(payload.primaryShadowVisibility, 0.0, 1.0)));
}